## Application configuration
#spring.application.name=ProjectCountries
#server.port=8080
#
## PostgreSQL Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/TestDb
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=668123
#
## JPA and Hibernate configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.defer-datasource-initialization=true
#
## (Optional) Enable the H2 console for testing purposes, remove if not needed
#spring.h2.console.enabled=false


# Application configuration
spring.application.name=ProjectCountries
server.port=8080

# H2 In-Memory Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# H2 Console (access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
#spring.sql.init.schema-locations=
spring.sql.init.mode=never
