spring.application.name=learn-spring-boot

management.endpoints.web.exposure.include=*

currency-service.url=http://defaulturl.com
currency-service.username=defaultusername
currency-service.key=defaultkey
